3.5 playground
meadowvale-secondary-school/SAIF pull request #10
Opened 2019-05-14 14:20 UTC by SaifA21

This is the completed 3.5 Playground.

2019-05-15 13:23 UTC, dlongmuir requested changes

2019-05-15 13:23 UTC, dlongmuir commented on 3 - Navigation/Lab - Enumerations.playground/Pages/1. Exercise - Enumerations.xcplaygroundpage/Contents.swift
> +let fourOfHearts = Card(suit: hearts, value: .four)
This line doesn't compile - it needs to be `.hearts` and `value:` is defined as `num:`

2019-05-15 13:23 UTC, dlongmuir commented on 3 - Navigation/Lab - Enumerations.playground/Pages/1. Exercise - Enumerations.xcplaygroundpage/Contents.swift
> +let fourOfHearts = Card(suit: hearts, value: .four)
Also, `.four` is not an `Int` so on line 59 is it supposed to be `var num: Value`?

2019-05-20 06:19 UTC, closed without merging

2019-05-20 06:19 UTC, SaifA21 commented
Closing PR 10 For PR 11